Repository geopython/geopython-workshop, pull requests merged in 2024-06, with the labels that each got.

#161 #156 rebuild and test Dockerfile and notebooks - minor updates scripts
  workshop/docker-compose-services.yml
  workshop/docker-compose.yml
  workshop/geopython-workshop-ctl.sh
  workshop/jupyter/build.log
Labels: bug

#162 #160 add wfs.get_schema example - localize WFS examples Estonia/Tartu
  workshop/jupyter/content/notebooks/10-remote-data.ipynb
  workshop/jupyter/content/notebooks/test/10-populated-places-ee.json
  workshop/jupyter/content/notebooks/test/10-populated-places-ro.json
Labels: enhancement

#163 #159 fix axis ordering in examples and localize to Estonia/Tartu
  workshop/jupyter/content/notebooks/07-visualization.ipynb
  workshop/jupyter/content/notebooks/test/07-folium-1.html
  workshop/jupyter/content/notebooks/test/07-folium-2.html
Labels: enhancement

#170 Closes #168
  workshop/jupyter/content/notebooks/05-raster-data.ipynb
  workshop/jupyter/content/notebooks/images/raster-matrix.jpg
Labels: bug, documentation
